### PR TITLE
Avoid using "global" explicitly

### LINKED ISSUE #204: Issue when using bundle.js where global throws error for setImmediate
I am trying to use Fluture in Codepen and the CDN bundle.js throws the following error:

`Reference Error: global is not defined`

The instance where global is being called is on the setImmediate function here: https://github.com/fluture-js/Fluture/blob/19febe13038ea5c9d6f2cc499d7b9052a334e611/dist/bundle.js#L2499

I was able to fix this error by wrapping an IIFE that passes the global object like this:

```
var setImmediate = (function(global) {
  return typeof global.setImmediate === 'function'
  ? global.setImmediate
  : /* istanbul ignore next: environment-specific */ setImmediate$1;
})(/*istanbul ignore next*/(commonjsGlobal || window || commonjsGlobal));
```

However, I didn't know if this was how it should be approached in the source file here: 
https://github.com/fluture-js/Fluture/blob/19febe13038ea5c9d6f2cc499d7b9052a334e611/src/internal/fn.js#L5

### PR DESCRIPTION
**Pull request by Avaq**
Fixes #204

### CODE REVIEW

**Comment by Avaq** [comment]
I tested it by compiling `dist/bundle.js`, including it in a web-page and constructing a Future. Should that be sufficient @wking-io?

**Comment by wking-io** [comment]
That should do the trick! Thank you for the quick fix and reply!

**Comment by wking-io** [comment]
@Avaq when will the CDN be updated with this version?

**Comment by Avaq** [comment]
I *just* published 8.0.1, which updated the CDN.

**Pull request merged**
